sudo: required
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - docker build -t exkute/deployer:latest .
  - if [ -z $TRAVIS_TAG ]; then docker build -t "exkute/deployer:$TRAVIS_TAG"; fi
  - docker push exkute/deployer:latest
  - if [ -z $TRAVIS_TAG ]; then docker push "exkute/deployer:$TRAVIS_TAG"; fi

