sudo: required
services:
  - docker

if: tag IS present
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - docker build --tag="exkute/deployer:latest" .
  - if [ -n "$TRAVIS_TAG" ]; then docker build --tag="exkute/deployer:$TRAVIS_TAG" .; fi
  - docker push exkute/deployer:latest
  - if [ -n "$TRAVIS_TAG" ]; then docker push "exkute/deployer:$TRAVIS_TAG"; fi

